# This is not a real Dockerfile, it only uses Dockerfile format 
# for compatibility with renovate.
# The lines are in format of `FROM image:tag@sha256 as name`

# planka
FROM ghcr.io/plankanban/planka:1.26.3@sha256:42c5e7a546d1cf082080fee06a922d1839157f479941a8a7c98e9d6a75c6d373 as planka
# listmonk
FROM docker.io/listmonk/listmonk:v5.1.0@sha256:67d032544aa0fe0d2e80eccd6c824175ec2b675bd732f32c970564606bdf0083 as listmonk
