inputs@{
    pkgs,
    config,
    ...
}:
let
    parser = import ./parser.nix inputs;
    strings = pkgs.lib.strings;
    lists = pkgs.lib.lists;

    list = parser.list;
    attrs = parser.attrs;

    settingsFormat = pkgs.formats.toml { };
    inspectToml = settingsFormat.generate "inspect.toml" attrs;

    generateHash = line: ''
        if [ $1 = "${line.name}" ]; then
            NAME=${(strings.replaceString ":" "_" line.digest)}
            if [ ! -f $DIR/$NAME.tgz ]; then
                ${pkgs.skopeo}/bin/skopeo copy docker://${line.repository}@${line.digest} docker-archive://$DIR/$NAME.tgz:${line.repository}:${line.tag} >> /dev/stderr
            fi
            echo "${line.name} = \"$(nix-hash --base64 --flat --type sha256 $DIR/$NAME.tgz)\";"
        fi
    '';
    generateHashes = pkgs.writeShellScriptBin "generate-hashes" ''
        set -Eeuo pipefail
        mkdir -p /tmp/images
        DIR=/tmp/images

        generate_hash() {
            ${pkgs.lib.concatLines (builtins.map generateHash list)}
        }

        if [ $# -eq 0 ]; then
            (
                echo "# This is an autogenerated file, run "just generate-hashes" to regenerate it"
                echo "# It's generated from Dockerfile next to it"
                echo "{"
                for name in ${strings.concatStringsSep " " (builtins.map (l: l.name) list)}
                do
                    echo -n "  "
                    generate_hash $name
                done
                echo "}"
            ) > $(${pkgs.lib.getExe config.flake-root.package})/podman/hashes.nix
        else
            while [ ! $# -eq 0 ]; do
                generate_hash $1
                shift
            done
        fi
    '';
in
{
    packages.generate-hashes = generateHashes;
    packages.inspect-hashes = pkgs.writeShellScriptBin "inspect-hashes" "cat ${inspectToml}";
}
