# This is an autogenerated file, run just generate-hashes to regenerate it
# It's generated from Dockerfile next to it
{
  planka = "43r3mTkGsPx/UPczfkgOO2CvQdr06IZyb9DKB4ll3p0=";
  listmonk = "GmYhWtyukzA8K+PSehtIcrRMRlxS3rj40uqqQr/TUlM=";
}
