# This is an autogenerated file, run just generate-hashes to regenerate it
# It's generated from Dockerfile next to it
{
  kanidm = "kXjXrcAAWMicNIjvy8IP7tqFyneQI+MTekCKsgbLX30=";
  forgejo = "odvqOKngBRAVL3QHe89aqRnGZME67Q8tRC6+sKQm8lI=";
  vaultwarden = "bYM03DrF2afjsbn/feKPkf23vzbmdwHvpdEAU6vaZ3E=";
  planka = "43r3mTkGsPx/UPczfkgOO2CvQdr06IZyb9DKB4ll3p0=";
}
